# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-08-02 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blk_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Company',
        ),
    ]
