# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-08-03 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blk_app', '0002_auto_20230802_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('l_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('loan_amount', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
