# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-08-03 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blk_app', '0005_auto_20230803_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan1',
            fields=[
                ('l_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('loan_amount', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('hash_value', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
