# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-08-03 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blk_app', '0006_auto_20230803_1501'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loan1',
            new_name='Loan',
        ),
    ]
