# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2024-03-23 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blk_app', '0007_auto_20230803_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('r_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('c_date', models.CharField(max_length=255)),
                ('c_time', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Bank',
            new_name='Patient',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
